import React, { createContext, useState, useEffect, useContext } from 'react';

const content = {
  en: {
    brand: "Sam Perfumes",
    navProcess: "Our Story",
    navEssence: "Essence",
    navConsult: "Custom Blend",
    navGallery: "Gallery",
    galleryTitle: "SAM Creations",
    galleryDesc: "A visual journey into our world of premium perfumery.",
    bookNow: "Contact Us",
    heroSubtitle: "Premium Fragrances",
    heroTitle: "Elegance in Every Drop",
    heroDesc: "SAM Perfumes (سام للعطور) offers an exclusive collection of compositions, bakhoor, and body mists tailored to your personality. Experience the essence of luxury.",
    beginJourney: "Explore Collection",
    section1Title: "The World of ",
    section1Span: "SAM",
    section1Desc: "We craft more than just scents; we bottle memories and emotions. From traditional Bakhoor to modern Hair Mists, our quality is unparalleled.",
    step1Title: "Selection",
    step1Desc: "Choose from our curated range of compositions and essential oils, sourced from the finest ingredients worldwide.",
    step2Title: "Blending",
    step2Desc: "Our artisans meticulously blend notes to create harmony, ensuring each batch meets the high standards of SAM.",
    step3Title: "Perfection",
    step3Desc: "Each bottle is a testament to our dedication, packaged with elegance and delivered to your doorstep.",
    qualitySubtitle: "Exquisite Quality",
    qualityTitle: "Finest Ingredients",
    qualityP1: "Luxury begins with the ingredients. We source the rarest ouds, musks, and florals to ensure your fragrance is long-lasting and unique.",
    qualityP2: "Our traditions meet modern techniques to bring you products like our signature Makhmariyat and premium Body Splashes.",
    exploreSourcing: "Our Ingredients",
    ctaTitle: "Find Your Signature Scent",
    ctaDesc: "Discover the collection that has captivated scent enthusiasts. From traditional to contemporary, SAM has it all.",
    reserveConsult: "Get Your Custom Blend",
    sourcingHeroTitle: "Ethical & Pure",
    sourcingDesc: "We pride ourselves on using pure materials that respect both tradition and nature.",
    contactHeroTitle: "Get in Touch",
    contactDesc: "Reach out to us for bulk orders, custom blends, or any inquiries about our premium collections.",
    processIntro: "Whether you seek the deep aroma of Bakhoor or the refreshing mist of a Body Splash, SAM is your destination for quality.",
    processDetail1: "Our range includes Hair Mists and Makhmariyat, designed to linger beautifully throughout the day.",
    essenceDetails: "We use high-concentration oils for our compositions, ensuring a rich fragrance profile that evolves on the skin.",
    consultationDetails: "Interested in a custom blend? Our experts can help you create a scent that is uniquely yours.",
    formName: "Full Name",
    formEmail: "Email Address",
    formMessage: "How can we help?",
    formSubmit: "Send Message",
    formSuccess: "Thank you. We will contact you shortly.",
    teamTitle: "The Artisans",
    teamDesc: "Meet the experts behind the SAM signature scents.",
    teamRole1: "Master Perfumer",
    teamName1: "SAM Founder",
    teamRole2: "Bakhoor Specialist",
    teamName2: "Ali Hassan",
    teamRole3: "Product Designer",
    teamName3: "Sarah Ahmed",
    reviewsTitle: "What They Say",
    reviewsDesc: "Customer experiences with SAM Perfumes.",
    review1: "\"The Bakhoor is the best I have ever used. It fills the room with such a rich, calming aroma.\"",
    reviewer1: "M. Abdelsalam",
    review2: "\"Their Hair Mist stays for hours. I get compliments everywhere I go. Truly premium!\"",
    reviewer2: "Laila K.",
    review3: "\"The Makhmariyat is so smooth and the fragrance is divine. A must-have in my daily routine.\"",
    reviewer3: "Fatma Z.",
    mapTitle: "Our Location",
    mapDesc: "Visit one of our branches to experience the fragrances in person.",
    address: "Ezbet Al Saaida, Abu Kabir, Al Sharqia Governorate",
    quickLinks: "Quick Links",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    shippingPolicy: "Shipping Policy",
    navCollection: "The Collection",
    filterAll: "All Categories",
    filterComposition: "Composition",
    filterMakhmariyat: "Makhmariyat",
    filterBodySplash: "Body Splash",
    filterHairMist: "Hair Mist",
    filterAirFresheners: "Air Fresheners",
    filterBakhoor: "Bakhoor",
    filterGenderAll: "All Genders",
    filterMen: "Men",
    filterWomen: "Women",
    filterUnisex: "Unisex",
    perfume1Name: "Oud Sam",
    perfume1Desc: "Our signature composition with deep woody notes and luxury oud.",
    perfume2Name: "Silk Makhmariya",
    perfume2Desc: "A smooth, velvet-like scented cream that leaves a lasting impression.",
    perfume3Name: "Tropical Splash",
    perfume3Desc: "A refreshing body splash with citrus and sea breeze notes.",
    perfume4Name: "Rose Hair Mist",
    perfume4Desc: "Delicate fragrance for your hair, infused with vitamins and floral notes.",
    perfume5Name: "Home Oud",
    perfume5Desc: "A powerful air freshener that brings the luxury of the orient home.",
    perfume6Name: "Royal Bakhoor",
    perfume6Desc: "A traditional incense experience with slow-burning, rich wooden chips.",
    noMatches: "No products found in this category.",
    deptSectionTitle: "Our Departments",
    deptSectionDesc: "Explore our exclusive range of premium fragrance products.",
    deptCompositionTitle: "Composition",
    deptCompositionDesc: "Custom fragrance blends crafted for your unique identity.",
    deptMakhmariyatTitle: "Makhmariyat",
    deptMakhmariyatDesc: "Luxurious scented creams for deep, long-lasting skin fragrance.",
    deptBodySplashTitle: "Body Splash",
    deptBodySplashDesc: "Light, refreshing mists to keep you feeling fresh all day.",
    deptHairMistTitle: "Hair Mist",
    deptHairMistDesc: "Gentle fragrance sprays designed specifically for hair care.",
    deptAirFreshenersTitle: "Air Fresheners",
    deptAirFreshenersDesc: "Premium home fragrances to elevate your living space.",
    deptBakhoorTitle: "Bakhoor",
    deptBakhoorDesc: "Traditional incense and oud chips for a truly royal atmosphere.",
    exploreBtn: "Explore",
    footerInfo: "Information"
  },
  ar: {
    brand: "سام للعطور",
    navProcess: "قصتنا",
    navEssence: "الخلاصة",
    navConsult: "تركيب خاص",
    navGallery: "المعرض",
    galleryTitle: "إبداعات سام",
    galleryDesc: "رحلة بصرية في عالمنا للعطور الفاخرة.",
    bookNow: "تواصل معنا",
    heroSubtitle: "عطور فاخرة",
    heroTitle: "الأناقة في كل قطرة",
    heroDesc: "سام للعطور (SAM Perfumes) تقدم مجموعة حصرية من التركيبات، البخور، ومعطرات الجسم المصممة لتناسب شخصيتك. جرب جوهر الفخامة.",
    beginJourney: "استكشف المجموعة",
    section1Title: "عالم ",
    section1Span: "سام",
    section1Desc: "نحن نصنع أكثر من مجرد روائح؛ نحن نعلب الذكريات والعواطف. من البخور التقليدي إلى معطرات الشعر الحديثة، جودتنا لا تضاهى.",
    step1Title: "الاختيار",
    step1Desc: "اختر من بين مجموعتنا المختارة من التركيبات والزيوت العطرية، المستوردة من أفضل المكونات عالميًا.",
    step2Title: "المزيج",
    step2Desc: "يقوم حرفيونا بمزج النوتات بدقة لخلق تناغم، مع ضمان مطابقة كل دفعة لمعايير سام العالية.",
    step3Title: "الإتقان",
    step3Desc: "كل زجاجة هي دليل على تفانينا، معبأة بأناقة ويتم توصيلها إلى باب منزلك.",
    qualitySubtitle: "جودة رائعة",
    qualityTitle: "أجود المكونات",
    qualityP1: "تبدأ الفخامة بالمكونات. نحن نستورد أندر أنواع العود والمسك والزهور لضمان أن يكون عطرك يدوم طويلاً وفريدًا.",
    qualityP2: "تلتقي تقاليدنا مع التقنيات الحديثة لنقدم لك منتجات مثل مخمرياتنا المميزة ومعطرات الجسم الفاخرة.",
    exploreSourcing: "مكوناتنا",
    ctaTitle: "ابحث عن عطرك المميز",
    ctaDesc: "اكتشف المجموعة التي أسرت عشاق الروائح. من التقليدي إلى المعاصر، لدى سام كل شيء.",
    reserveConsult: "احصل على تركيبتك الخاصة",
    sourcingHeroTitle: "أخلاقي ونقي",
    sourcingDesc: "نحن نفخر باستخدام مواد نقية تحترم التقاليد والطبيعة.",
    contactHeroTitle: "تواصل معنا",
    contactDesc: "تواصل معنا لطلبات الجملة، التركيبات الخاصة، أو أي استفسارات حول مجموعاتنا المميزة.",
    processIntro: "سواء كنت تبحث عن رائحة البخور العميقة أو رذاذ معطر الجسم المنعش، سام هي وجهتك للجودة.",
    processDetail1: "تشمل مجموعتنا معطرات الشعر والمخمريات، المصممة لتبقى جميلة طوال اليوم.",
    essenceDetails: "نحن نستخدم زيوتًا عالية التركيز لتركيباتنا، مما يضمن ملفًا عطريًا غنيًا يتطور على البشرة.",
    consultationDetails: "هل أنت مهتم بتركيبة خاصة؟ يمكن لخبرائنا مساعدتك في إنشاء رائحة فريدة بك تمامًا.",
    formName: "الاسم الكامل",
    formEmail: "البريد الإلكتروني",
    formMessage: "كيف يمكننا مساعدتك؟",
    formSubmit: "إرسال الرسالة",
    formSuccess: "شكرًا لك. سنتواصل معك قريبًا.",
    teamTitle: "الحرفيون",
    teamDesc: "تعرف على الخبراء وراء روائح سام المميزة.",
    teamRole1: "خبير عطور",
    teamName1: "مؤسس سام",
    teamRole2: "متخصص بخور",
    teamName2: "علي حسن",
    teamRole3: "مصمم منتجات",
    teamName3: "سارة أحمد",
    reviewsTitle: "ماذا يقولون",
    reviewsDesc: "تجارب العملاء مع سام للعطور.",
    review1: "\"البخور هو الأفضل الذي استخدمته على الإطلاق. يملأ الغرفة برائحة غنية ومهدئة.\"",
    reviewer1: "م. عبد السلام",
    review2: "\"معطر الشعر الخاص بهم يدوم لساعات. أحصل على إطراءات في كل مكان. فاخر بحق!\"",
    reviewer2: "ليلى ك.",
    review3: "\"المخمرية ناعمة للغاية والرائحة إلهية. لا بد منها في روتيني اليومي.\"",
    reviewer3: "فاطمة ز.",
    mapTitle: "موقعنا",
    mapDesc: "قم بزيارة أحد فروعنا لتجربة العطور شخصيًا.",
    address: "عزبة الصعايدة، أبو كبير، محافظة الشرقية",
    quickLinks: "روابط سريعة",
    privacyPolicy: "سياسة الخصوصية",
    termsOfService: "شروط الخدمة",
    shippingPolicy: "سياسة الشحن",
    navCollection: "المجموعة",
    filterAll: "جميع الأقسام",
    filterComposition: "التركيب",
    filterMakhmariyat: "مخمريات",
    filterBodySplash: "badySplash",
    filterHairMist: "hairmist",
    filterAirFresheners: "معطرات",
    filterBakhoor: "بخور",
    filterGenderAll: "للجميع",
    filterMen: "رجالي",
    filterWomen: "نسائي",
    filterUnisex: "محايد",
    perfume1Name: "عود سام",
    perfume1Desc: "تركيبتنا المميزة مع نوتات خشبية عميقة وعود فاخر.",
    perfume2Name: "مخمرية الحرير",
    perfume2Desc: "كريم معطر ناعم كالحرير يترك انطباعًا يدوم.",
    perfume3Name: "تروبيكال سبلاش",
    perfume3Desc: "معطر جسم منعش مع نوتات الحمضيات ونسيم البحر.",
    perfume4Name: "روز هير ميست",
    perfume4Desc: "عطر رقيق لشعرك، غني بالفيتامينات ونوتات الزهور.",
    perfume5Name: "هوم عود",
    perfume5Desc: "معطر جو قوي يجلب فخامة الشرق إلى منزلك.",
    perfume6Name: "بخور ملكي",
    perfume6Desc: "تجربة بخور تقليدية مع رقائق خشبية غنية وبطيئة الاحتراق.",
    noMatches: "لم يتم العثور على منتجات في هذا القسم.",
    deptSectionTitle: "أقسامنا",
    deptSectionDesc: "استكشف مجموعتنا الحصرية من منتجات العطور الفاخرة.",
    deptCompositionTitle: "التركيب",
    deptCompositionDesc: "تركيبات عطرية مخصصة مصنوعة لتعكس هويتك الفريدة.",
    deptMakhmariyatTitle: "مخمريات",
    deptMakhmariyatDesc: "مخمريات فاخرة للتعطر العميق والمستمر للبشرة.",
    deptBodySplashTitle: "badySplash",
    deptBodySplashDesc: "رذاذ خفيف ومنعش يمنحك انتعاشًا طوال اليوم.",
    deptHairMistTitle: "hairmist",
    deptHairMistDesc: "بخاخات عطرية لطيفة مصممة خصيصًا للعناية بالشعر.",
    deptAirFreshenersTitle: "معطرات",
    deptAirFreshenersDesc: "معطرات جو فاخرة لرفع مستوى مساحتك المعيشية.",
    deptBakhoorTitle: "بخور",
    deptBakhoorDesc: "بخور تقليدي ورقائق عود لأجواء ملكية حقيقية.",
    exploreBtn: "استكشف",
    footerInfo: "معلومات"
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('ar');

  const toggleLanguage = () => {
    setLang((prev) => (prev === 'en' ? 'ar' : 'en'));
  };

  useEffect(() => {
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLanguage, t: content[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
